version: '3.8'
services:
  deudas-container:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    env_file:
      - .env
    networks:
      - microservices-network
networks:
  microservices-network:
    driver: bridge
